# cart-1 position
float32 x
float32 y
float32 z
# cart-2 position
float32 x_2
float32 y_2
float32 z_2
# cart parameters
float32 speed_left
float32 speed_right
float32 angular_velocity_left
float32 angular_velocity_right
# cart-2 parameters
float32 speed_left_2
float32 speed_right_2
float32 angular_velocity_left_2
float32 angular_velocity_right_2
# sensors value (??)(fixed-length/variable-length)
float64 camera_img
float64 lidar_array 

# time inf
time time_iter
duration duration_iter
